apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openclaw

resources:
  - namespace.yaml
  - litellm/deployment.yaml
  - litellm/service.yaml
  - memory/postgres-statefulset.yaml
  - memory/redis-deployment.yaml
  - openclaw/gateway-deployment.yaml
  - openclaw/gateway-service.yaml

commonLabels:
  app.kubernetes.io/part-of: agentes-ai-on-clouds
  app.kubernetes.io/managed-by: kustomize
